import os
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

def summarize_email(email_body):
    print(f"Analyzing email: {email_body}")
    summary = "This is a placeholder summary generated by AI."
    return summary
